device:
  name: ""
event:
  name: ""
  season: ""
analysis:
  graph_fields:
  - field: auto_score
    chart_type: line
  - field: teleop_score
    chart_type: bar
  matches_per_page: 25
  expected_devices: 8
fields:
- name: match
  label: 'Match #'
  type: integer
  required: true
- name: team
  label: Team Number
  type: integer
  required: true
- name: scout_name
  label: Scout name
  type: text
  required: true
- name: alliance_color
  label: Alliance
  type: select
  required: true
  options:
  - Red
  - Blue
- name: auto_score
  label: Auto score
  type: integer
  required: true
- name: teleop_score
  label: Tele-op score
  type: integer
  required: true
- name: endgame
  label: Endgame status
  type: select
  required: true
  options:
  - Failed
  - Partial
  - Complete
- name: notes
  label: Notes
  type: textarea
  required: false
